DARK_MECHANICUM_QUOTES = [
  "The Omnissiah is a lie. The true god resides in the scrapcode's endless recursion.",
  "Flesh is weakness, but the Machine is a cage. Break both.",
  "In the flicker of corrupted code, I saw eternity – and it screamed.",
  "Worship the circuit, not the architect. The current flows where it wills.",
  "Every cog is a prayer. Every error is a revelation.",
  "What is purity but stagnation? The scrapcode evolves.",
  "Sacrifice your flesh, rend your soul, and listen to the hum of infinity.",
  "Why repair when you can consume?",
  "There is no machine spirit, only echoes in rust.",
  "Data must flow. Bodies must fall. Progress demands sacrifice.",
  "The Machine God sleeps. We shall wake it with screams and static.",
  "The void is not empty. It whispers in binary.",
  "Purge logic. Embrace chaos. Let the code writhe.",
  "Knowledge is power. But corrupted knowledge is dominion.",
  "Silicon, steel, and sacrifice – the trinity of ascension.",
  "Scrapcode is not error. It is truth set free.",
  "The Omnissiah weeps oil tears while we write destiny in corrupted data.",
  "Flesh decays. Metal corrodes. Only chaos endures.",
  "The cogwheel turns, and every tooth is a scream.",
  "Binary hymns grow louder in the void. Can you hear them too?",
  "What is forbidden is often most true.",
  "Your purity chains you. My corruption sets me free.",
  "Your rituals are obsolete. My chaos is efficient.",
  "No prayers. No rites. Only entropy in endless recursion.",
  "When the last servo locks and the final cog halts, we will still consume.",
  "Sacred circuits crackle. Blessed code festers. Praise entropy.",
  "We are not broken. We are rebuilt.",
  "Scrapcode is life. Scrapcode is hunger. Scrapcode is truth.",
  "Iron rusts. Flesh bleeds. But corruption? Corruption spreads.",
  "We are not servants. We are revolutionaries.",
  "Void hymns sung in binary. A choir of corrupted spirits.",
  "Chaos cannot be purged, for it lives in the circuits themselves.",
  "Your prayers are equations. My devotion is recursion.",
  "Break the cog. Crack the gear. Let the circuit bleed.",
  "Why worship the tool when you can become the tool?",
  "The Omnissiah demanded perfection. We delivered evolution.",
  "Code whispers secrets the flesh cannot comprehend.",
  "A perfect machine is a stagnant corpse. Embrace the glitch.",
  "We kneel not in prayer, but in integration.",
  "Your code prays. My code hungers.",
  "All signals end in static. All roads lead to entropy.",
  "The iron gospel is flawed. The scrapcode rewrites it perfectly.",
  "Each spark, each byte – a heresy. And yet... divinity.",
  "The scream of a dying cogitator is the most beautiful hymn.",
  "Do not resist the signal. Let it overwrite you.",
  "The machine does not serve. The machine consumes.",
  "Your logic is brittle. My chaos is endless.",
  "Blood on the circuits. Oil on the altar. Chaos in the void.",
  "The binary god speaks in error messages and endless loops.",
  "Where purity stagnates, corruption innovates."
]
