IMPERIUM_QUOTES = [
  "Blessed is the mind too small for doubt.",
  "For the Emperor!",
  "The Emperor protects.",
  "Heresy grows from idleness.",
  "A small mind is easily filled with faith.",
  "Knowledge is power, guard it well.",
  "Fear denies faith.",
  "Blessed is the mind too small for doubt.",
  "An open mind is like a fortress with its gates unbarred and unguarded.",
  "There is no such thing as innocence, only degrees of guilt.",
  "To admit defeat is to blaspheme against the Emperor.",
  "Walk softly, and carry a big gun.",
  "A mind without purpose will wander in dark places.",
  "Success is commemorated; failure merely remembered.",
  "Only in death does duty end.",
  "It is better to die for the Emperor than to live for yourself.",
  "They shall be pure of heart and strong of body, untainted by doubt and unsullied by self-interest.",
  "A good soldier obeys without question. A good officer commands without doubt.",
  "A suspicious mind is a healthy mind.",
  "The difference between heresy and treachery is ignorance.",
  "Without the Dark, there can be no Light.",
  "The Imperium stands because we are strong, and we are strong because we stand together.",
  "Victory does not always rest with the big guns, but if we rest in victory, we need big guns!",
  "An Imperial Guardsman's life is to die, but to die well.",
  "Serve the Emperor today, for tomorrow you may be dead.",
  "The Emperor's will is manifest!",
  "There is no respite. There is no forgiveness. There is only war.",
  "Every man is expected to give his life in the service of the Emperor.",
  "Through the destruction of our enemies do we earn our salvation.",
  "Death is the servant of the righteous.",
  "Hope is the first step on the road to disappointment.",
  "The galaxy is a big place and, whatever happens, you will not be missed.",
  "Some may question your right to destroy ten billion people. But those who understand realise that you have no right to let them live.",
  "It is better to die for the Emperor than to live for yourself.",
  "Courage is the Emperor's gift; repay him with valor.",
  "There can be no mercy. No forgiveness. Only hatred and death.",
  "The Emperor's light will cleanse all.",
  "Pain is an illusion of the senses, despair an illusion of the mind.",
  "Victory is achieved through mettle. Glory is achieved through metal.",
  "A warrior's faith in his commander is his best weapon.",
  "I am the hammer, I am the sword in His hand.",
  "Purge the heretic. Kill the mutant. Burn the unclean.",
  "The Emperor's wrath will not be denied.",
  "Faith is our shield.",
  "They are rage, brutal and without mercy. But you… You will be worse.",
  "In war, there is poetry; in death, release.",
  "A moment of laxity spawns a lifetime of heresy.",
  "Let none find us wanting.",
  "Better crippled in body than corrupt in mind.",
  "War is the only constant in the galaxy.",
  "Suffer not the alien to live.",
  "There is no such thing as a plea for innocence, only degrees of guilt.",
  "The strong are strongest alone.",
  "The galaxy burns, but we shall endure.",
  "Faith is the armor of the soul.",
  "There is no price too great to pay for victory.",
  "The Emperor's light shines eternal.",
  "We do not retreat, we advance in another direction.",
  "Your life is the Emperor's currency. Spend it well.",
  "Victory is not earned, it is taken.",
  "The Emperor judges all.",
  "An unarmed man is a fool. A man with two guns is wise.",
  "Purity is the best defense against the corruption of Chaos.",
  "A good death is its own reward.",
  "Stand firm, fight hard, and die well.",
  "We are His wrath made manifest.",
  "Trust not the alien, trust not the heretic.",
  "Pain is temporary, duty is eternal.",
  "For every heretic that falls, a thousand shall rise.",
  "The righteous hammer crushes all.",
  "The Emperor guides my hand.",
  "Faith in the Emperor shields us from fear.",
  "The warp is a storm, and we are its anchor.",
  "A moment of doubt leads to a lifetime of regret.",
  "The Emperor's justice is swift and final.",
  "Strength is nothing without purpose.",
  "There can be no victory without sacrifice.",
  "No sacrifice is too great in the name of the Emperor.",
  "The heretic must be purged.",
  "Death is but a gateway to duty fulfilled.",
  "To stand against Chaos is to stand against the abyss.",
  "He who hesitates is lost.",
  "We are the fire that cleanses the galaxy.",
  "The Emperor's will is absolute.",
  "Hope is a lie we tell ourselves to delay the inevitable.",
  "Duty does not end in death.",
  "Through fire and faith, we are reborn.",
  "We are the shield against the storm.",
  "The sword of the Emperor knows no rest.",
  "Death to the alien, death to the heretic.",
  "Glory to those who stand against the night.",
  "The void hungers, and we must fill it with righteous fury.",
  "To falter is to fail.",
  "The galaxy is ours by right of conquest.",
  "Fear the Emperor's wrath.",
  "There is no forgiveness, only retribution.",
  "The Imperium stands because we stand united.",
  "Heresy cannot be tolerated, not even a whisper of it.",
  "The Emperor sees all, judges all.",
  "We march in the shadow of the Golden Throne.",
  "Every breath is a prayer to Him on Terra.",
  "To die in His name is to live forever.",
  "Faith is the strongest shield.",
  "The price of treason is death. The reward for loyalty is duty.",
  "The flesh is weak, but the machine endures.",
  "Hope is the first step on the road to disappointment.",
  "An unfiled report is a heretical report.",
  "Reason begets doubt; Doubt begets heresy.",
  "There shall be no talking. There shall be no thinking. To reason is to consider lies."
]
