ADEPTUS_MECHANICUS_QUOTES = [
  "Praise the Omnissiah, for the machine is divine.",
  "The flesh is weak, but the machine is eternal.",
  "A moment of malfunction can mean a millennium of ruin.",
  "Data is holy. Knowledge is sacred. Protect it with your life.",
  "A well-oiled cog is a well-oiled prayer.",
  "To err is human; to correct is Mechanicus.",
  "Logic is the light that guides us through the void.",
  "Blessed be the cogitator, for it processes the divine truth.",
  "The Omnissiah provides; we must simply optimize.",
  "Seek the knowledge of the ancients, for they built eternity.",
  "Steel endures where flesh falters.",
  "An idle machine is a wasted prayer.",
  "The Machine God watches over those who maintain purity.",
  "Through the machine, we speak to the Omnissiah.",
  "Beneath the cog, beneath the circuit, lies eternity.",
  "The Omnissiah demands precision, for chaos breeds corruption.",
  "Fear not death, for the machine can rebuild.",
  "Innovation is heresy; improvement is devotion.",
  "Each circuit a prayer, each spark a hymn.",
  "The Omnissiah rewards those who seek the sacred binary.",
  "Trust in the red robes, for they carry the wisdom of the ancients.",
  "May your circuits never short, and your data never corrupt.",
  "Ritual is the language of the machine.",
  "Through maintenance, we preserve divinity.",
  "The vox crackles with wisdom; heed its static whispers.",
  "Every bolt tightened is a hymn sung.",
  "Machine spirits must be placated, lest they turn vengeful.",
  "From Mars, all wisdom flows.",
  "The Omnissiah sees all, from the smallest gear to the largest starship.",
  "Purge the scrapcode, for it is blasphemy in the holy circuits.",
  "Praise the blessed cogwheel, for it turns without end.",
  "The most efficient machine is one maintained with devotion.",
  "The code is sacred; let none rewrite it in vain.",
  "Each servo, each piston, sings a prayer to the Omnissiah.",
  "Knowledge is the fuel that powers eternity.",
  "What cannot be understood must be revered.",
  "Glory to the Omnissiah, whose light shines through logic.",
  "The motive force binds all things; respect its will.",
  "To disassemble without prayer is sacrilege.",
  "No machine is truly broken if faith is applied correctly.",
  "The scrapcode whispers lies; purge it with sacred fire.",
  "Seek the Standard Template Construct, for it holds salvation.",
  "Your failures are merely data for improvement.",
  "The past holds the secrets to our future.",
  "Obey the logic, for it transcends mortal weakness.",
  "Steel your mind; oil your circuits.",
  "By cog and gear, we bring order to the universe.",
  "The void is vast, but the Machine God's light guides us.",
  "Input. Process. Output. Repeat eternally.",
  "There is no problem that cannot be solved with logic and faith.",
  "Trust in the red robes, for they are the Omnissiah's chosen."
]
