ORK_QUOTES = [
  "WAAAGH!",
  "If it bleeds, we can krump it!",
  "Da bigga da gun, da bigga da boom!",
  "Red ones go fasta!",
  "Green is best!",
  "Oi, stop muckin' about and shoot somethin'!",
  "It ain't stupid if it works!",
  "We'z gonna stomp 'em good!",
  "I'z got a plan… it's called 'more dakka'!",
  "Orkses is never defeated in battle. If we win we win, if we die we die fighting so it don't count. If we runs for it we don't lose neither, cos we can come back for annuver go, see!",
  "Wotz betta than a big gun? Two big guns!",
  "Oi, who stole me teef?",
  "An Ork with a plan? Dat's proppa suspicious!",
  "Da humies think dey so smart, but we got dakka!",
  "We'z gonna fight, we'z gonna win, and then we'z gonna have lunch.",
  "Stop shootin', ya gits! You'll ruin da surprise!",
  "No plan survives contact with the enemy… unless it involves more dakka.",
  "Orks iz neva beaten in battle! If we run away, it just means we'z comin' back fer anuvver go.",
  "We'z da best, 'cause we'z green!",
  "'Ere we go, 'ere we go, 'ere we go!",
  "Wot's a 'strategy'? Can ya eat it?",
  "Shoot first, loot later!",
  "Gork blesses da brutal, Mork blesses da cunning.",
  "Oi, zog off!",
  "You ain't a real Ork until ya'z got a choppa bigger than ya head.",
  "Orks don't have problems, just more fings to krump.",
  "More dakka solves all problems!",
  "If it's shiny, it's ours!",
  "It's not about winning, it's about fightin' and winning.",
  "Stop runnin', we'z tryin' to shoot ya!",
  "You lot got more guts than brains, and that's why I likes ya!",
  "Dakka dakka dakka!",
  "Oi, dat's my hat!",
  "Why build one gun when ya can build a dozen?",
  "We're da biggest, we're da strongest, and we'z gonna win!",
  "Big choppa, small brain.",
  "Can we eat it? No? Then shoot it!",
  "If ya can't fix it with duct tape, use more dakka.",
  "We Orks is made for fightin' and winnin'!",
  "Green iz da color of victory!",
  "Who needs stealth when ya got explosions?",
  "Less talkin', more stompin'!",
  "Oi, who said Orks can't fly? Watch dis!",
  "We'z da meanest and da greenest!",
  "If at first ya don't succeed, use more dakka.",
  "Wot's dat humie word? 'Subtle'? Sounds squishy.",
  "Give 'em da chop!",
  "Everyfing is betta wiv dakka.",
  "Stop askin' questions, just krump it!",
  "Orks is da best!",
  "Dis fight ain't over until I says it's over!",
  "Oi! Who said we can't loot dis tank?",
  "The bigger the explosion, the better the day.",
  "If it's shiny, it's mine!",
  "Green iz best, everyone else is just jealous.",
  "Don't worry, boss, I've got a cunning plan… WAAAGH!",
  "We ain't runnin' away, we'z advancing in another direction.",
  "Why talk when ya can shoot?",
  "Me gun's bigger than yours!",
  "More choppin', less talkin'!",
  "We'z da Orks, and Orks don't lose!",
  "I ain't dead yet, so dat means I won.",
  "Oi, ya git! Gimme back me shoota!",
  "Who needs orders when ya got enthusiasm?",
  "Da humies keep buildin' stuff… so we keep smashin' it!",
  "If it's not explodin', it's not workin' right.",
  "'Ere we go, 'ere we go, 'ere we go!",
  "Smash it first, ask questions later.",
  "If we'z yell louder, we'z fight better!",
  "Orks iz neva beaten! If we die, we just come back meaner.",
  "If it ain't broke, we'll fix it till it is.",
  "Red paint makes everything fasta!",
  "I'z da biggest Ork, so I'm da boss!",
  "Oi, stop finkin' and start krumpin'!",
  "More teef means more dakka!",
  "If ya can't shoot it, punch it. If ya can't punch it, burn it.",
  "One Ork is good, two Orks is better, and a mob is unstoppable.",
  "Less sneakin', more stompin'!",
  "A proppa Waaagh! needs proppa noise!",
  "Gork and Mork are watchin', so don't mess up!",
  "Who needs armor when ya got attitude?",
  "Shoot 'em, stomp 'em, and take their stuff!",
  "Oi, stop touchin' my bitz!",
  "Zoggin' 'ell, dis is gonna be fun!",
  "More dakka always fixes da problem.",
  "You call dat a boom? I'll show ya a BOOM!",
  "If it's not Orky, it's not right.",
  "I'z da loudest, so I must be da smartest.",
  "Why sneak when you can stomp?",
  "If it moves, krump it. If it stops movin', loot it.",
  "No fight's too big if ya got enough boyz.",
  "We'z born to fight and fight to win!",
  "If ya can't build it, loot it!",
  "Orks never lose. We either win or come back for more fightin'!",
  "Why aim when ya can spray bullets everywhere?",
  "Gimme more dakka, less yap!",
  "If ya run outta bullets, throw da gun!",
  "Every day's a good day for a Waaagh!",
  "Oi, boss! Look at dat big shiny humie thing! Can I shoot it?",
  "When in doubt, WAAAGH!",
  "A fight ain't over till the last Ork stops yellin'!"
]
